descriptor-schema-version: 2.0
 
info:
  name: HelloWorld 
  description: "A very simple python Hello World app"
  version: "0.6"
 
app:
  type: paas

  resources:
    profile: t2.micro
 
    network:
      - 
        interface-name: eth0

# Specify runtime and startup
  startup:
    runtime: python 
    runtime-version: 2.7
    target: main.py
